version: "3.3"
services:
  mongodb:
    container_name: mongodb
    ports:
      - "27017:27017"
    image: mongo:4.0.10
    environment:
      - MONGODB_USER="user"
      - MONGODB_PASS="pass"
    volumes:
      - "mongodb-data:/data/db"
  # mongoclient:
  #   container_name: mongoclient
  #   ports:
  #     - "4000:3000"
  #   image: mongoclient/mongoclient:latest
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: 'always'
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_PASSWORD="pass"
      - MYSQL_USER="user"
      - MYSQL_DATABASE=testDB

volumes:
  mongodb-data: {}