version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - jenkins_lab
  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts
    ports:
      - "9000:9000"
    environment:
      SONARQUBE_USERNAME: admin
      SONARQUBE_PASSWORD: admin
    networks:
      - jenkins_lab
networks:
  jenkins_lab:

volumes:
  jenkins_data: